# Generated by Django 4.1.3 on 2022-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventhall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=255)),
                ('purp', models.CharField(max_length=255)),
                ('edate', models.DateField()),
                ('stime', models.TimeField()),
            ],
        ),
    ]
