# Generated by Django 4.1.3 on 2022-11-27 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apartment_desc', models.TextField()),
                ('bhk', models.IntegerField(default=0)),
                ('location', models.TextField()),
                ('contact', models.ForeignKey(limit_choices_to={'user_type': 'adm'}, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('assigned', models.ForeignKey(limit_choices_to={'user_type': 'emp'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('req_user', models.ForeignKey(limit_choices_to={'user_type': 'ten'}, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='manager.utilities')),
            ],
            options={
                'unique_together': {('assigned', 'date', 'time')},
            },
        ),
    ]
