# Generated by Django 4.1.3 on 2022-11-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_utilities_apartments_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
