# Generated by Django 4.1.3 on 2022-11-27 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_apartments_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='contact',
            field=models.ForeignKey(limit_choices_to={'user_type': 'adm'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
