# Generated by Django 4.1.3 on 2022-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_apartments_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='bhk',
            field=models.IntegerField(default=1),
        ),
    ]
