# Generated by Django 4.1.3 on 2022-11-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_apartments_bhk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('util', 'date', 'time')},
        ),
    ]
