# Generated by Django 4.1.3 on 2022-11-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_bookings_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
