# Generated by Django 4.1.3 on 2022-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_bookings_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together={('req_user', 'util')},
        ),
    ]
