# Generated by Django 4.1.3 on 2022-11-27 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_user_apartment_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='price',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
