# Generated by Django 4.1.3 on 2022-11-30 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_user_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenantrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenrequests', to='manager.apartments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenrequests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
